---
version: '3.8'

networks:
  mynetwork:
    name: "${APP_NAME}-net"

services:
  php:
    container_name: "${APP_NAME}-php"
    labels:
      local.project: "${APP_NAME}"
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: always
    ports:
      - "${HTTPD_LISTEN_PORT}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    volumes:
      - "${APP_FOLDER}/mission_0:/var/www/html"
      #- "${APP_FOLDER}:/var/www/html"
      - ./apache/vhosts:/etc/apache2/sites-enabled
      - ./apache/logs:/var/log/apache2:cached
      - ./tmp:/tmp
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - mynetwork
    links:
      - pgsql

  pgsql:
    container_name: "${APP_NAME}-pgsql"
    labels:
      local.project: "${APP_NAME}"
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      PGUSER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    healthcheck:
      test: pg_isready -h 127.0.0.1 -u $${POSTGRES_USER}
      interval: 5s
      retries: 5
    networks:
      - mynetwork
    #depends_on:
    #  - php

volumes:
  db_data:

